---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgClKr8utF2DxBpfN+3kAWAW9s6JFNBGghXCJcvKdNWkgMpHhjax61Rq3RjeQE5MOgK6ajODoku3ySWRjO6gR9bLJvxVVDR/+unJ/fxPx9cNUEbVdL3NqZEZjawEqxYoQs5LS818IpwuscErdYk+Y64uu8sSQDBAMnbshMmbRmryUnKSxS1BEn4TMGTbNH0IDwJKRbYjVl836tIgM0/lAk9L9tDidL3sMJW326g6xf6UWBMYY1cZLVo3k38xGu2XPagrgLZaBXAZ/hU1oP7hEZH7jkv7+BVZDji0vnbsgXEgB5Im+ihEzztSanXk5u4Zj3QAnP5cVPEgeshr1w10aCB8FecEMGSLI2JuyWbqHG9wwBAp5JOud8mPsJhOk0yFCi0qw1nfFYbbB72zd+zqcq/G5j9EbkzLcgI3DsIizWhCs74J+3cuuspoNsCCM5PQQechO9yYJOYx8NRCxuPM3usOZVX4wlUpPBZDTYamY7QmrAkw7bM3qiHrbbfcXCDH/biGi0cvY7r+oLac+PlJrpYwLY3PozqcbI4MShiGb36UCX7XeXlcEN8liCOrHudbLlNGIdKvxMUtA3mQQCeGcBt8DR2hVYT/3ozTEcNtIpY7uSDzeOh6h9Z3DNuBVOT5mIo7ZbIMhfqocHCISNv819WaWktDFn3DYrwitXSDV6PLr1g49h6eTYs9p4vnpIapcjGtYfICzeWO6Q==
  template:
    metadata:
      name: grafana-secret
      namespace: monitoring
    type: Opaque
