---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBb5ZCgkz55Du5RZ+cq3oIwdZuDuIzycM280FwE3nuVTvd3zGsdaWvZzUnrm7wslBNcM4UiZtfnpv1xX23te1f9Bbm82XCE+h/8Ff1bzmXdn2EDkO3NZTLBNUc1Kg0jqyNZfEvw6O4DxOiqJvZhAsjs66lGfRseoOO2p6tXek/30cD7JRoKLZaH0iXlvB0/EWLf0XbyN0K/iexPYs3QtSXRmWbzJPq6lSyIdTdFQoBcT/A+ZhyRZXeSmYKiyXuIVOO5bQnsfAXJYzprcf6lX4P+nwYEaPWA0sDLW4Nxp9JTG1K+u9srz+/KcU5AbVSzv6MNlXBlYMrKhQwF98EDrOAYrl0YaUEq0v5fe5kSvHcgLbKSmuZxN5KcHrWMIivoK6ePWkmpEIp7y4ZXapHaGxxrMtTk89/Ld7jKEGyVfafKc+5zXWOIAzdGpAeUm8Aj7E7azJz3e999K0IzlhJgZs2YTqtGZfqofy1FOpCituDl8kBN03kUtZsshIPrdemV0iibsaxbUsU3t4FwZODzVuwRlTnw9VODeh6t85wP6YvmCfavL49Bj9C0qWqB+xW82E4meHiaUaQHjeOffmpVLzAXmJ5LZwC6JwbtYMp+xjIMYxnyv+cjMITIdNLisEA/VItANw9h7f00Ydnp01e+C697SH4K+H99YrFMR+PqafYclod3p7d2STX0Uy819CHXTPWkvOObz1Rw+A==
  template:
    metadata:
      name: grafana-secret
      namespace: monitoring
    type: Opaque
