---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: production
spec:
  encryptedData:
    REDIS_PASSWORD: AgCNu0ZnztgqmyH4ZYoWf/6b09WvpaD/V+cUJ9JoIiJOdj1Q6RYya6LAd78fQzY9nYHlRA8O+eHUr/lJfk2gNTl8Mpvj+7niK8Ed2imGmS8ZPc2sOt82IeKxtP8Bte5x8oCozeNKQHjdHw0UZI1FDpgaQ/zNRxo7BAjtFoVo8VglXXNzVCEHTZ7V1EaZJstFKxW9PcPIHlk2OH47do6iRacL5o/wALBQd4oswY6G2EgPDT7foyPz0mZah2OosRUh9EWkkZSVBJEiZ1gARVKI8pT9rYJnmx5ZHLQdcQ4FabynVRn2O1Qi07QzDnDk5jvF+z/4C3AnLw+0946kXdUFCrmjnVmsF8nkusvA+wOKcIL2jJIObqzUiDV+CXj3yEAucwWw/oy1yvYtbfwOI94hUYUwnsUYuyxgW0ycUWLgvWQtve+aErw4abKWrqj6iIbq6StQ6WwcXkP/XussoqDQPTSTzaw3mbdQnTU2j0rdWVdypwvok6rQraD96cx56ahqw+He1KOydetwdiCR/xv0NKfzXq0/ewQfQ+h2fyZ+Y9fIBTJn5/XnGiOIpZRUIpcoybfITnAcNydkh+LST77fCjT1Tso+VkPWWxWPPFYHzaL3MULHpZwF00M6cxw7isVPhVzOzDcGwGWxCUP7PClzXsZ5sfZGEYmqFNtosA1YVCBNJ2npe3Vxi+TzHGQe7jOETsC/ny4hPsf/wM9k5fsV
  template:
    metadata:
      name: app-secret
      namespace: production
    type: Opaque
