---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: app-secret
  namespace: production
spec:
  encryptedData:
    REDIS_PASSWORD: AgARvyHykuybpm+ybkdi/ayxpBRoPg/xVg41zu3itrb4t7+7wPLGf/IKZVTIr8K26krsi18OV0+L4Pd8HWuu4zRGZ1OfSsd0rl/zOP4RjCJYD2g4VOf9hEBWATFRNfoq+JWLHIVXGWxLNHr22fnvyWfy28NjsCgrv5WB1AJm8UwGtKqIhz5Gy/3fqyEkTVVkH+I3D95eG1vf3m1AdnZw3GslN7/nRGdnjcJQUsrJiTQa+4IH+4MCiy2DI+HnkN8JsUCQOMk0pJoubNVXEw/wFgRNxQ/V8g5cov5phwhulCCpn+HAFDWUcEA/Netrhs3XYipLBP3SMrlXcP27TYddw7LqQXlYLfRCxoTDD1hBYQ7Qy/Yfev3bncJVXCClDvY0No7Mpluu/ju7p3UofgLXOl5+bMapxk7CXk0FCe+K5mJ20lP19Rss8ngJM/FstwHWbCDzwQWGsAd4GxzPJTz63ZNBZAiRXT7LubAzxbUxAs6N9h1cuxtcgwPiNqB9TR+etihOCRjnSwbTvKHpHo2cy3ojqR6cVuG7mAK+XBp/4oa/t42dgYVIhULGLZhNnVux9ZN3obAMuNhz0jbIkxSmYx+b4C9ufD3+Tv44RuKTeIlhQ9vGN8kmmlyrtUI3m46FTSUlnVJZs8/jUojqJjBUogCSkZ752ZOnYun1lLB75/i+7FlEhH0CagE9vseu1wR9fhiSNRjk8nsKSJmNaXI1
  template:
    metadata:
      name: app-secret
      namespace: production
    type: Opaque
